name: jenkins_api_client2_func_tests
git: git://github.com/asghaier/jenkins_api_client2.git
ref: master
script:
 - bundle install
 - rake unit_tests
 - rake func_tests
 notification_email: ahmed@sghaier.com
 notification_email_for_every_unstable: true
